#ifndef __TOUCHSCREEN_FW__
#define __TOUCHSCREEN_FW__

#if defined(CONFIG_BOARD_BOLTON)
#define SYN_ECW_FW_NAME	"ECW_S7020_6P0_1920_1080_36393034_P853A13_PR2082467.img"
#define SYN_JUNDA_FW_NAME	"JUNDA_S7020_6P0_1920_1080_36453033_P853A13_PR2082467.img"
#elif defined(CONFIG_BOARD_FLORIST)
#define SYN_ECW_FW_NAME	"ECW_S7020_6P0_1920_1080_36393033_P853A13_PR2082467.img"
#define SYN_JUNDA_FW_NAME	"JUNDA_S7020_6P0_1920_1080_36453033_P853A13_PR2082467.img"
#elif defined(CONFIG_BOARD_STOLLEN)
#define SYN_OFILM_FW_NAME "ZTE_P840A20_Ofilm_6p0_1920_1280_S3603_DS5_17.0.0.1085_PR2559122_55343235.img"
#define SYN_DIJING_FW_NAME "ZTE_P840A20_Dijing_6p0_1920_1280_S3603_DS5_17.0.0.1085_PR2559122_55493131.img"
#elif defined(CONFIG_BOARD_PEONY)
#define SYN_DIJING_FW_NAME  "ZTE_P817A22_DJN_5P5_1280_720_S3603_DS5_17.0.0.1085_PR2592280_55493136.img"
#define SYN_OFILM_FW_NAME  "ZTE_P817A22_Ofilm_5P5_1280_720_S3603_DS5_17.0.0.1085_PR2649320_55343139.img"
#elif defined(CONFIG_BOARD_PRIMROSE)
#define SYN_JUNDA_FW_NAME	"ZTE_P853A92_JDC_10P_1920_1200_S7060_DS4_3.6.4.64_PR2394177_52453035.img"
#define SYN_GUOXIAN_FW_NAME	"KD_S7060_10P_1920_1200_52513035_P853A92_V2_PR2394177.img"
#define SYN_DIJING_FW_NAME	"ZTE_P853A92_DJ_10P_1920_1200_S7060_DS4_3.6.4.64_PR2394177_52493036.img"
#elif defined(CONFIG_BOARD_CROCUS)
#define SYN_OFILM_FW_NAME "ZTE_P840T21_Ofilm_6P0_1920_1080_S3603_DS5_17.0.0.1085_PR2605936_55343033.img"
#define SYN_ECW_FW_NAME "ZTE_P840T21_ECW_6P0_1920_1080_S3603_DS5_17.0.0.1085_PR2559122_55393034.img"
#elif defined(CONFIG_BOARD_PROLINE)
#define SYN_DIJING_FW_NAME  "ZTE_P817A12_Dijing_5P5_1280_720_S3603_DS5_17.0.0.1085_PR2605936_55493035.img"
#define SYN_HELITECH_FW_NAME  "ZTE_P817A12_Holitech_5P5_1280_720_S3603_DS5_17.0.0.1085_PR2605936_55523034.img"
#elif defined(CONFIG_BOARD_WARP8)
#define SYN_DIJING_FW_NAME  "ZTE_P817A12_Dijing_5P5_1280_720_S3603_DS5_17.0.0.1085_PR2605936_55493035.img"
#define SYN_HELITECH_FW_NAME  "ZTE_P817A12_Holitech_5P5_1280_720_S3603_DS5_17.0.0.1085_PR2605936_55523034.img"
#elif defined(CONFIG_BOARD_COCONUT)
#define SYN_OFILM_FW_NAME  "ZTE_Z6400_Lead_Ofilm_6P0_1920_1080_S3603_DS5_17.0.0.1085_PR2697865_55343532.img"
#elif defined(CONFIG_BOARD_MAXXL2)
#define SYN_LEAD_FW_NAME  "ZTE_Z6410S_CSOT_6P_2160_1080_TD4310_DS5_12.6.0_PR2759843_58353036_0417.img"
#else
#define SYN_TPK_FW_NAME		""
#define SYN_TURLY_FW_NAME	""
#define SYN_SUCCESS_FW_NAME	""
#define SYN_OFILM_FW_NAME	""
#define SYN_LEAD_FW_NAME	""
#define SYN_WINTEK_FW_NAME	""
#define SYN_LAIBAO_FW_NAME	""
#define SYN_CMI_FW_NAME		""
#define SYN_ECW_FW_NAME		""
#define SYN_GOWORLD_FW_NAME	""
#define SYN_BAOMING_FW_NAME	""
#define SYN_EACHOPTO_FW_NAME	""
#define SYN_MUTTO_FW_NAME	""
#define SYN_JUNDA_FW_NAME	""
#define SYN_BOE_FW_NAME	""
#define SYN_TIANMA_FW_NAME	""
#define SYN_SAMSUNG_FW_NAME  ""
#define SYN_DIJING_FW_NAME  ""
#define SYN_LCE_FW_NAME	""
#define SYN_GUOXIAN_FW_NAME	""
#define SYN_HELITECH_FW_NAME	""
#define SYN_JDI_FW_NAME	""
#define SYN_HUAXINGDA_FW_NAME	""
#define SYN_TOPTOUCH_FW_NAME	""
#define SYN_GVO_FW_NAME	""
#define SYN_WALLY_PANEL_FW_NAME ""

#define FTC_TPK_FW_NAME		""
#define FTC_TURLY_FW_NAME	""
#define FTC_SUCCESS_FW_NAME	""
#define FTC_OFILM_FW_NAME	""
#define FTC_LEAD_FW_NAME	""
#define FTC_WINTEK_FW_NAME	""
#define FTC_LAIBAO_FW_NAME	""
#define FTC_CMI_FW_NAME		""
#define FTC_ECW_FW_NAME		""
#define FTC_GOWORLD_FW_NAME	""
#define FTC_BAOMING_FW_NAME	""
#define FTC_JUNDA_FW_NAME	""
#define FTC_JIAGUAN_FW_NAME	""
#define FTC_MUDONG_FW_NAME	""
#define FTC_EACHOPTO_FW_NAME	""
#define FTC_AVC_FW_NAME	""

#define GTP_SENSOR_ID_1_FW_NAME		""
#define GTP_SENSOR_ID_2_FW_NAME		""
#define GTP_SENSOR_ID_3_FW_NAME		""
#define GTP_SENSOR_ID_4_FW_NAME		""
#define GTP_SENSOR_ID_5_FW_NAME		""
#define GTP_SENSOR_ID_6_FW_NAME		""

#define CY_TPK_FW_NAME		""
#define CY_TURLY_FW_NAME	""
#define CY_SUCCESS_FW_NAME	""
#define CY_OFILM_FW_NAME	""
#define CY_LEAD_FW_NAME	""
#define CY_WINTEK_FW_NAME	""
#define CY_LAIBAO_FW_NAME	""
#define CY_CMI_FW_NAME		""
#define CY_ECW_FW_NAME		""
#define CY_GOWORLD_FW_NAME	""
#define CY_BAOMING_FW_NAME	""
#define CY_JUNDA_FW_NAME	""
#define CY_JIAGUAN_FW_NAME	""
#define CY_MUDONG_FW_NAME	""
#define CY_EACHOPTO_FW_NAME	""
#endif

#ifndef SYN_TPK_FW_NAME
#define SYN_TPK_FW_NAME		""
#endif
#ifndef SYN_TURLY_FW_NAME
#define SYN_TURLY_FW_NAME	""
#endif
#ifndef SYN_SUCCESS_FW_NAME
#define SYN_SUCCESS_FW_NAME	""
#endif
#ifndef SYN_OFILM_FW_NAME
#define SYN_OFILM_FW_NAME	""
#endif
#ifndef SYN_LEAD_FW_NAME
#define SYN_LEAD_FW_NAME	""
#endif
#ifndef SYN_WINTEK_FW_NAME
#define SYN_WINTEK_FW_NAME	""
#endif
#ifndef SYN_LAIBAO_FW_NAME
#define SYN_LAIBAO_FW_NAME	""
#endif
#ifndef SYN_CMI_FW_NAME
#define SYN_CMI_FW_NAME		""
#endif
#ifndef SYN_ECW_FW_NAME
#define SYN_ECW_FW_NAME		""
#endif
#ifndef SYN_GOWORLD_FW_NAME
#define SYN_GOWORLD_FW_NAME	""
#endif
#ifndef SYN_BAOMING_FW_NAME
#define SYN_BAOMING_FW_NAME	""
#endif
#ifndef SYN_EACHOPTO_FW_NAME
#define SYN_EACHOPTO_FW_NAME	""
#endif
#ifndef SYN_MUTTO_FW_NAME
#define SYN_MUTTO_FW_NAME	""
#endif
#ifndef SYN_JUNDA_FW_NAME
#define SYN_JUNDA_FW_NAME	""
#endif
#ifndef SYN_BOE_FW_NAME
#define SYN_BOE_FW_NAME	""
#endif
#ifndef SYN_TIANMA_FW_NAME
#define SYN_TIANMA_FW_NAME	""
#endif
#ifndef SYN_SAMSUNG_FW_NAME
#define SYN_SAMSUNG_FW_NAME  ""
#endif
#ifndef SYN_DIJING_FW_NAME
#define SYN_DIJING_FW_NAME  ""
#endif
#ifndef SYN_LCE_FW_NAME
#define SYN_LCE_FW_NAME	""
#endif
#ifndef SYN_GUOXIAN_FW_NAME
#define SYN_GUOXIAN_FW_NAME	""
#endif
#ifndef SYN_HELITECH_FW_NAME
#define SYN_HELITECH_FW_NAME	""
#endif
#ifndef SYN_JDI_FW_NAME
#define SYN_JDI_FW_NAME ""
#endif
#ifndef SYN_HUAXINGDA_FW_NAME
#define SYN_HUAXINGDA_FW_NAME	""
#endif
#ifndef SYN_TOPTOUCH_FW_NAME
#define SYN_TOPTOUCH_FW_NAME	""
#endif
#ifndef SYN_GVO_FW_NAME
#define SYN_GVO_FW_NAME	""
#endif
#ifndef SYN_WALLY_PANEL_FW_NAME
#define SYN_WALLY_PANEL_FW_NAME	""
#endif

#ifndef FTC_TPK_FW_NAME
#define FTC_TPK_FW_NAME		""
#endif
#ifndef FTC_TURLY_FW_NAME
#define FTC_TURLY_FW_NAME	""
#endif
#ifndef FTC_SUCCESS_FW_NAME
#define FTC_SUCCESS_FW_NAME	""
#endif
#ifndef FTC_OFILM_FW_NAME
#define FTC_OFILM_FW_NAME	""
#endif
#ifndef FTC_LEAD_FW_NAME
#define FTC_LEAD_FW_NAME	""
#endif
#ifndef FTC_WINTEK_FW_NAME
#define FTC_WINTEK_FW_NAME	""
#endif
#ifndef FTC_LAIBAO_FW_NAME
#define FTC_LAIBAO_FW_NAME	""
#endif
#ifndef FTC_CMI_FW_NAME
#define FTC_CMI_FW_NAME		""
#endif
#ifndef FTC_ECW_FW_NAME
#define FTC_ECW_FW_NAME		""
#endif
#ifndef FTC_GOWORLD_FW_NAME
#define FTC_GOWORLD_FW_NAME	""
#endif
#ifndef FTC_BAOMING_FW_NAME
#define FTC_BAOMING_FW_NAME	""
#endif
#ifndef FTC_JUNDA_FW_NAME
#define FTC_JUNDA_FW_NAME	""
#endif
#ifndef FTC_JIAGUAN_FW_NAME
#define FTC_JIAGUAN_FW_NAME	""
#endif
#ifndef FTC_MUDONG_FW_NAME
#define FTC_MUDONG_FW_NAME	""
#endif
#ifndef FTC_EACHOPTO_FW_NAME
#define FTC_EACHOPTO_FW_NAME	""
#endif

#ifndef FTC_AVC_FW_NAME
#define FTC_AVC_FW_NAME	""
#endif

#ifndef GTP_SENSOR_ID_1_FW_NAME
#define GTP_SENSOR_ID_1_FW_NAME		""
#endif
#ifndef GTP_SENSOR_ID_2_FW_NAME
#define GTP_SENSOR_ID_2_FW_NAME		""
#endif
#ifndef GTP_SENSOR_ID_3_FW_NAME
#define GTP_SENSOR_ID_3_FW_NAME		""
#endif
#ifndef GTP_SENSOR_ID_4_FW_NAME
#define GTP_SENSOR_ID_4_FW_NAME		""
#endif
#ifndef GTP_SENSOR_ID_5_FW_NAME
#define GTP_SENSOR_ID_5_FW_NAME		""
#endif
#ifndef GTP_SENSOR_ID_6_FW_NAME
#define GTP_SENSOR_ID_6_FW_NAME		""
#endif

#ifndef CY_TPK_FW_NAME
#define CY_TPK_FW_NAME		""
#endif
#ifndef CY_TURLY_FW_NAME
#define CY_TURLY_FW_NAME	""
#endif
#ifndef CY_SUCCESS_FW_NAME
#define CY_SUCCESS_FW_NAME	""
#endif
#ifndef CY_OFILM_FW_NAME
#define CY_OFILM_FW_NAME	""
#endif
#ifndef CY_LEAD_FW_NAME
#define CY_LEAD_FW_NAME	""
#endif
#ifndef CY_WINTEK_FW_NAME
#define CY_WINTEK_FW_NAME	""
#endif
#ifndef CY_LAIBAO_FW_NAME
#define CY_LAIBAO_FW_NAME	""
#endif
#ifndef CY_CMI_FW_NAME
#define CY_CMI_FW_NAME		""
#endif
#ifndef CY_ECW_FW_NAME
#define CY_ECW_FW_NAME		""
#endif
#ifndef CY_GOWORLD_FW_NAME
#define CY_GOWORLD_FW_NAME	""
#endif
#ifndef CY_BAOMING_FW_NAME
#define CY_BAOMING_FW_NAME	""
#endif
#ifndef CY_JUNDA_FW_NAME
#define CY_JUNDA_FW_NAME	""
#endif
#ifndef CY_JIAGUAN_FW_NAME
#define CY_JIAGUAN_FW_NAME	""
#endif
#ifndef CY_MUDONG_FW_NAME
#define CY_MUDONG_FW_NAME	""
#endif
#ifndef CY_EACHOPTO_FW_NAME
#define CY_EACHOPTO_FW_NAME	""
#endif

/*
固件名按照这个顺序排列
*/
enum TOUCH_MOUDLE {
	TPK = 0,
	TRULY,
	SUCCESS,
	OFILM,
	LEAD,
	WINTEK,
	LAIBAO,
	CMI,
	ECW,
	GOWORLD,
	BAOMING,
	EACHOPTO,
	MUTTO,
	JUNDA,
	BOE,
	TIANMA,
	SAMSUNG,
	DIJING,
	LCE,
	GUOXIAN,
	HELITECH,
	JDI,
	HUAXINGDA,
	TOPTOUCH,
	GVO,
	WALLY_PANEL,
	UNKNOWN = 0xff
};
#define SYN_MOUDLE_NUM_MAX 30
#define FTC_MOUDLE_NUM_MAX 16
#define GTP_MOUDLE_NUM_MAX 6
#define CY_MOUDLE_NUM_MAX 15

#endif
