#drivers/input/touchscreen/focaltech_ts/focaltech_test
#
#Makefile for test module
#
# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/focaltech_touch/firmware_config/$(CONFIG_TS_FIRMWARE)/
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_test_config_ft5x46.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_test_ft5x46.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_test_config_ft6x36.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_test_ft6x36.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_test_config_ft8006.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_test_ft8006.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_test_supported_ic.o
