snd-soc-tfa9890-objs := tfa98xx.o
snd-soc-tfa9890-objs += tfa_container.o
snd-soc-tfa9890-objs += tfa_dsp.o
snd-soc-tfa9890-objs += tfa9888_init.o
snd-soc-tfa9890-objs += tfa9891_init.o
snd-soc-tfa9890-objs += tfa9897_init.o
snd-soc-tfa9890-objs += tfa9890_init.o
snd-soc-tfa9890-objs += tfa9887B_init.o
snd-soc-tfa9890-objs += tfa9887_init.o

obj-$(CONFIG_ZTE_FEATURE_NXP9890_SMART_PA)	+= snd-soc-tfa9890.o
