ccflags-y += -I$(srctree)/drivers/input/touchscreen/Mstar_Touch_v5_7/firmware_config/$(CONFIG_TS_FIRMWARE)/
obj-y += IniParser/
obj-y	+=  MsgLib.o
obj-y	+=  MsgControl.o
obj-y	+=  MpTest.o
obj-y	+=  OpenTest.o
obj-y	+=  ShortTest.o
obj-y	+=  WaterProofTest.o
obj-y	+=  MsgUtility.o
obj-y	+=  TestCommon.o
obj-y	+=  CreateCSV.o
obj-y	+=  my_parser.o

