#gt1151 touchpanel driver


obj-$(CONFIG_TOUCHSCREEN_GT1151)	+= gt1x.o

obj-$(CONFIG_TOUCHSCREEN_GT1151)	+= gt1x_extents.o

obj-$(CONFIG_TOUCHSCREEN_GT1151)	+= gt1x_generic.o
#gt1151 update file
obj-$(CONFIG_TOUCHSCREEN_GT1151)	+= gt1x_update.o
#debug tool
obj-$(CONFIG_TOUCHSCREEN_GT1151)	+= gt1x_tools.o
