#drivers/input/touchscreen/focaltech_touch/focaltech_test/src
#
# Makefile for test module
#
# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/focaltech_touch/firmware_config/$(CONFIG_TS_FIRMWARE)/
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_test.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_test_main.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_test_ini.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_test_global.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_test_detail_threshold.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TP_TEST) += focaltech_ic_table.o
